"""Regenerate the decision table from results/*.json.

This script is the reason no number in the README is hand-typed. If you change an
experiment, you rerun this and the table changes. If a row cannot be built from a
results file, it does not go in the table.
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from legalintel.utils.results import load_all  # noqa: E402

# The intellectual backbone: one row per decision the project makes.
DECISIONS = [
    ("Document classification", "classify.baselines", "f1_macro"),
    ("Probability quality", "classify.calibration", "brier"),
    ("NER", "ner.baselines", "f1"),
    ("Retrieval", "retrieval.methods", "ndcg@10"),
    ("Processing", "processing.scaling", "docs_per_sec"),
    ("Storage", "storage.options", "p95_latency_ms"),
]
LOWER_IS_BETTER = {"brier", "log_loss", "p95_latency_ms"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="README_RESULTS.md")
    ap.add_argument("--split", default="dev", help="'dev' while iterating, 'test' after freeze")
    args = ap.parse_args()

    runs = [r for r in load_all() if r.get("split") == args.split]
    by_exp: dict[str, list[dict]] = defaultdict(list)
    sig = {r["variant"]: r["metrics"] for r in load_all("classify.significance")}
    for r in runs:
        by_exp[r["experiment"]].append(r)

    lines = [
        f"# Results (`{args.split}` split)",
        "",
        "Generated by `make report`. Do not edit by hand.",
        "",
        "| Decision | Methods tested | Metric | Winner | Margin | Significant? |",
        "|---|---|---|---|---|---|",
    ]

    for label, exp, metric in DECISIONS:
        rows = [r for r in by_exp.get(exp, []) if metric in r.get("metrics", {})]
        if not rows:
            lines.append(f"| {label} | _not run_ | {metric} | — | — | — |")
            continue
        reverse = metric not in LOWER_IS_BETTER
        rows.sort(key=lambda r: r["metrics"][metric], reverse=reverse)
        best, runner_up = rows[0], (rows[1] if len(rows) > 1 else None)
        margin = (
            f"{best['metrics'][metric] - runner_up['metrics'][metric]:+.4f}"
            if runner_up else "—"
        )
        if runner_up:
            key = f"{best['variant']}_vs_{runner_up['variant']}"
            rev = f"{runner_up['variant']}_vs_{best['variant']}"
            entry = sig.get(key) or sig.get(rev)
        else:
            entry = None
        sig_s = "not tested" if entry is None else (
            f"p={entry['p_value']:.4f}"
            if entry["p_value"] < 0.05
            else f"n.s. (p={entry['p_value']:.3f})"
        )
        lines.append(
            f"| {label} | {', '.join(r['variant'] for r in rows)} | {metric} "
            f"| **{best['variant']}** ({best['metrics'][metric]:.4f}) | {margin} | {sig_s} |"
        )

    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} from {len(runs)} result files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
