"""Generate a review batch: sample new docs (excluding ones already labeled),
run the built extract_entities() on each to produce candidate labels, and
write both a human-readable doc file and a pre-filled labels CSV for the
user to confirm/correct rather than label from scratch.

Candidates come from OUR OWN rule-based extractor (regex, not an LLM) --
already validated against 1000 real docs and against the first 30 hand-
labeled docs. The human's job is to catch what the rules got wrong or
missed, which is what makes the final labels a real gold standard rather
than a rubber stamp on the code's own output.

Usage:
    python scripts/generate_review_batch.py --input data/processed/ledgar_60000.parquet \
        --existing-n 30 --new-n 70
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from legalintel.ner.extract import extract_entities, load_pipeline


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True)
    ap.add_argument("--id-col", default="doc_id")
    ap.add_argument("--text-col", default="text")
    ap.add_argument("--existing-n", type=int, default=30, help="size of the original hand-labeled batch, to exclude")
    ap.add_argument("--existing-seed", type=int, default=42)
    ap.add_argument("--new-n", type=int, default=70)
    ap.add_argument("--new-seed", type=int, default=43)
    ap.add_argument("--out-dir", default="data/ner_labeling")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_parquet(args.input, columns=[args.id_col, args.text_col])

    existing_sample = df.sample(n=min(args.existing_n, len(df)), random_state=args.existing_seed)
    existing_ids = set(existing_sample[args.id_col])

    remaining = df[~df[args.id_col].isin(existing_ids)]
    new_sample = remaining.sample(
        n=min(args.new_n, len(remaining)), random_state=args.new_seed
    ).reset_index(drop=True)

    print(f"loading spaCy pipeline...")
    nlp = load_pipeline()

    docs_path = out_dir / "review_batch_docs.txt"
    candidates_path = out_dir / "review_batch_candidates.csv"

    with open(docs_path, "w") as doc_f, open(candidates_path, "w") as cand_f:
        doc_f.write(
            "REVIEW BATCH -- candidate labels were auto-generated by extract_entities().\n"
            "For each doc, check the [CANDIDATE] lines against the text:\n"
            "  - correct candidate -> leave its row in review_batch_candidates.csv as-is\n"
            "  - wrong candidate    -> delete that row from the CSV\n"
            "  - missed entity      -> add a new row to the CSV yourself, same format\n"
            "doc_index continues from where the first batch (000-029) left off.\n"
            "\n" + "=" * 70 + "\n\n"
        )
        cand_f.write("doc_index,entity_text,label\n")

        n_candidates = 0
        for i, row in new_sample.iterrows():
            idx = args.existing_n + i  # continue numbering from 030
            text = str(row[args.text_col]).strip()
            doc_f.write(f"=== DOC {idx:03d} (id={row[args.id_col]}) ===\n")
            doc_f.write(text + "\n")

            ents = extract_entities(text, nlp=nlp)
            candidates = [e for e in ents if e.label in ("GOVERNING_LAW", "DEFINED_TERM")]
            if candidates:
                doc_f.write("[CANDIDATES]: " + "; ".join(f"{e.label}={e.text!r}" for e in candidates) + "\n")
                for e in candidates:
                    cand_f.write(f"{idx:03d},{e.text},{e.label}\n")
                    n_candidates += 1
            else:
                doc_f.write("[CANDIDATES]: (none)\n")
            doc_f.write("\n")

    print(f"wrote {len(new_sample)} docs to {docs_path}")
    print(f"wrote {n_candidates} candidate labels to {candidates_path}")
    print(f"\nnext: open both files, review each [CANDIDATES] line against its doc text,")
    print(f"correct {candidates_path} (delete wrong rows, add missed ones), then merge")
    print(f"it with labels_template.csv once you're done.")


if __name__ == "__main__":
    main()
